### ISSUE TITLE
Report a Problem not working

### ISSUE THREAD

**Issue by nathankota** [agrc/broadband#91] opened 2019-09-16 13:04 UTC
The "Report a Problem" button does not allow users to "Send" an issue. 

![image](https://user-images.githubusercontent.com/15659642/64960255-32a26e80-d850-11e9-8b0d-2870b959da4d.png)

**Comment by stdavis** [comment] 2019-09-24 22:55
Duplicate of #83

**Comment by stdavis** [comment] 2019-09-26 14:31
https://github.com/agrc/SendEmailService/issues/9

**Comment by stdavis** [comment] 2019-09-26 19:47
This has been fixed.

**Closed by stdavis** 2019-09-26 19:47 UTC
Labels: bug
