### ISSUE TITLE
Provider Filter

### ISSUE THREAD

**Issue by jpechmann** [agrc/broadband#47] opened 2016-01-20 00:21 UTC
The provider name filter on broadband.utah.gov/map is not working. I've tried chrome and firefox. The other filters (transtech and speed) appear to be working fine. 

Let me know if you have trouble reproducing or anything.

Thanks!

**Comment by stdavis** [comment] 2016-01-23 18:06
Duplicate of #44

**Closed by stdavis** 2016-01-23 18:06 UTC
Labels: duplicate
